config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :payments
  resources :categories
  
  authenticated :user do
    root 'categories#index', as: :authenticated_root
  end

  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_one_attached :icon
  has_many :payments, dependent: :destroy
  belongs_to :user
  validates :name, presence: true
  validates :icon, presence: true
  validates :user_id, presence: true

  def total_amount(user)
    payments.where(user_id: user.id).sum(:amount)
  end

  def sorted_payments(user)
    payments.where(user_id: user.id).order(created_at: :desc)
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :amount, presence: true
  validates :amount, numericality: { greater_than: 0 }
  validates :category_id, presence: true
  validates :name, presence: true

  def payment_date
    created_at.strftime('%d %b %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories, dependent: :destroy
  has_many :payments, dependent: :destroy
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.includes(:user).where(user: current_user)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @payments = @category.sorted_payments(current_user)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_path, notice: 'Category was successfully deleted.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[show edit update destroy]

  # GET /payments or /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1 or /payments/1.json
  def show; end

  # GET /payments/new
  def new
    @payment = Payment.new
    @categories = Category.includes(:user).where(user: current_user)
  end

  # GET /payments/1/edit
  def edit; end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)
    @payment.user = current_user

    respond_to do |format|
      if @payment.save
        format.html { redirect_to category_path(@payment.category), notice: 'Payment was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:name, :amount, :category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to categories_path, notice: 'Account successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_category.html.erb
<div class="flex items-center mb-10 bg-white rounded-lg">
  <% if category.icon.attached? %>
  <%= image_tag category.icon, class: "w-32 h-32 object-cover rounded-lg" %>
  <% else %>
  <img
      src="https://cdn.tailgrids.com/1.0/assets/images/cards/card-01/image-01.jpg"
      alt="image"
      class="w-32 h-32"
      />
  <% end %>
  <div class="p-8 ">
    <h3 class="mb-4 font-semibold sm:text-base md:text-xl"><%= category.name %></h3>
    <p class="text-base leading-relaxed text-body-color">Total payments: <%= category.total_amount(current_user) %></p>
  </div>
</div> 

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :name, class: "block mb-3 text-base font-medium" %>
    <%= form.text_field :name, class: "w-full border-[1.5px] border-form-stroke rounded-lg py-3 px-5 font-medium text-body-color placeholder-body-color outline-none focus:border-primary active:border-primary transition" %>
  </div>

  <div class="mb-6">
    <%= form.label :icon, class: "block mb-3 text-base font-medium" %>
    <%= form.file_field :icon, direct_upload: true, class: "w-full border-[1.5px] border-form-stroke rounded-lg font-medium outline-none focus:border-primary active:border-primary transition cursor-pointer bg-white file:bg-white file:border-0 file:border-r file:border-solid file:border-collapse file:border-form-stroke file:py-3 file:px-5 file:mr-5 file:text-body-color file:cursor-pointer file:hover:bg-primary file:hover:bg-opacity-10" %>
  </div>

  <div>
    <%= form.submit class: "px-10 py-4 text-base font-normal text-center text-white rounded-md cursor-pointer lg:px-8 xl:px-10 bg-primary hover:bg-opacity-90" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<%= render "shared/session_header", title: "Categories", pathway: root_path %>

<section class="px-6 py-10">
  <% @categories.each do |category| %>
    <%= link_to category_path(category) do %>
      <%= render category %>
    <% end %>
  <% end %>
  <%= link_to new_category_path do %>
    <div class="inline-flex items-center justify-center p-4 mt-10 text-base font-normal text-center text-white rounded-md cursor-pointer bg-primary hover:bg-opacity-90">
      New Category
    </div>
  <% end %>
</section>

app/views/categories/new.html.erb
<%= render "shared/session_header", title: "New Category", pathway: root_path %>

<div class="bg-[#f5f6f8] h-full pt-6 px-10">
<%= render "form", category: @category %>
</div>

app/views/categories/show.html.erb
<%= render "shared/session_header", title: @category.name, pathway: root_path %>

<section class="px-6 py-10">
  <%= render @category %>
  <div class="w-5/6 mx-auto">
    <h2 class="w-full mb-10 font-semibold text-center">Payments</h2>
    <% @payments.each do |payment| %>
      <%= render payment %>
    <% end %>
  </div>
  <div class="flex justify-between mt-10">
    <%= link_to new_payment_path do %>
      <div class="inline-flex items-center justify-center p-4 text-base font-normal text-center text-white rounded-md cursor-pointer bg-primary hover:bg-opacity-90">
        Add new payment
      </div>
    <% end %>

    <%= button_to "Delete category", @category, method: :delete, class: "p-4 text-base font-normal text-center text-white rounded-md cursor-pointer bg-primary hover:bg-opacity-90" %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budgit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="min-h-screen max-w-2xl mx-auto text-[#434B54] border font-normal capitalize bg-[#a7a2ba]">
    <% if alert %><p class="w-full px-2 py-4 text-base text-center rounded text-[#CD5D5D] bg-[#feeaea] alert"><%= alert %></p><% end %>
    <main class="min-h-screen ">
      <%= yield %>
    </main>
  </body>
</html>

app/views/payments/_form.html.erb
<%= form_with(model: payment) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :name, class: "block mb-3 text-base font-medium" %>
    <%= form.text_field :name, class: "w-full border-[1.5px] border-form-stroke rounded-lg py-3 px-5 font-medium text-body-color placeholder-body-color outline-none focus:border-primary active:border-primary transition" %>
  </div>

  <div class="mb-6">
    <%= form.label :amount, class: "block mb-3 text-base font-medium" %>
    <%= form.number_field :amount, class: "w-full border-[1.5px] border-form-stroke rounded-lg py-3 px-5 font-medium text-body-color placeholder-body-color outline-none focus:border-primary active:border-primary transition" %>
  </div>

  <div class="mb-6">
    <%= form.label :category, class: "block mb-3 text-base font-medium" %>
    <%= form.collection_select :category_id, categories, :id, :name, {}, {class: "w-full border-[1.5px] border-form-stroke rounded-lg py-3 px-5 font-medium text-body-color placeholder-body-color outline-none focus:border-primary active:border-primary transition"}  %>
  </div>

  <div>
    <%= form.submit class: "px-10 py-4 text-base font-normal text-center text-white rounded-md cursor-pointer lg:px-8 xl:px-10 bg-primary hover:bg-opacity-90" %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>" class="flex flex-col p-4 mb-10 text-base bg-white rounded">
  <div class="flex justify-between w-full mb-4">
    <h3><%= payment.name %></h3> 
    <p class="font-semibold leading-relaxed">Amount: <%= payment.amount %></p>
  </div>
  <p><%= payment.payment_date %></p>
</div> 

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Payments</h1>

<div id="payments">
  <% @payments.each do |payment| %>
    <%= render payment %>
    <p>
      <%= link_to "Show this payment", payment %>
    </p>
  <% end %>
</div>

<%= link_to "New payment", new_payment_path %>

app/views/payments/new.html.erb
<%= render "shared/session_header", title: "New Payment", pathway: :back %>

<div class="bg-[#f5f6f8] h-full pt-6 px-10">
<%= render "form", payment: @payment, categories: @categories %>
</div>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>

app/views/shared/_header.html.erb
<div class="flex items-center justify-between px-4 py-6 text-white h-14 bg-primary">
  <%= link_to prev do %>
    <%= image_tag "left-arrow.png" %>
  <% end %>
  <p class="font-bold uppercase"><%= title %></p>
  <input type="submit" value="<%= value %>" form="new_user" class="cursor-pointer">
</div>

app/views/shared/_session_header.html.erb
<div class="flex items-center justify-between px-4 py-6 text-white h-14 bg-primary">
  <%= link_to(pathway) do %>
    <%= image_tag "left-arrow.png" %>
  <% end %>
  <p class="font-bold uppercase"><%= title %></p>
  <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
</div>

app/views/welcome/index.html.erb
<div class="flex flex-col justify-around h-screen p-6 bg-[#857ea3]" %>
<%= image_tag 'logo.png', alt: 'logo', class: 'mx-auto', width: '300' , height: '300' %>

<div class="flex flex-row gap-3 text-center button-placeholder mx-auto">
  <%= link_to new_user_session_path do %>
    <div class="p-4 rounded bg-[#3778C2] text-white ">
      LOG IN
    </div>
  <% end %>
  <%= link_to new_user_registration_path do %>
    <div class="p-4 rounded bg-[#3778C2] text-white" >
      SIGN UP
    </div>
  <% end %>
</div>
</div>